/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package tkj.android.homecontrol.mythmote;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int down=0x7f020000;
        public static final int icon=0x7f020001;
        public static final int left=0x7f020002;
        public static final int media=0x7f020003;
        public static final int right=0x7f020004;
        public static final int settings=0x7f020005;
        public static final int square=0x7f020006;
        public static final int starsmall=0x7f020007;
        public static final int up=0x7f020008;
    }
    public static final class id {
        public static final int Button01=0x7f060004;
        public static final int Button02=0x7f060005;
        public static final int Button03=0x7f060006;
        public static final int Button04=0x7f060008;
        public static final int Button05=0x7f060009;
        public static final int Button06=0x7f06000a;
        public static final int Button07=0x7f06000f;
        public static final int Button08=0x7f060011;
        public static final int Button09=0x7f060012;
        public static final int Button10=0x7f060013;
        public static final int Button11=0x7f060015;
        public static final int EditText01=0x7f060019;
        public static final int LinearLayout01=0x7f060017;
        public static final int ScrollView01=0x7f060000;
        public static final int TableLayout01=0x7f060002;
        public static final int TableLayout02=0x7f060018;
        public static final int TableRow01=0x7f060003;
        public static final int TableRow02=0x7f060007;
        public static final int TableRow03=0x7f06000b;
        public static final int TableRow04=0x7f06000d;
        public static final int TableRow05=0x7f060010;
        public static final int TableRow06=0x7f060014;
        public static final int TableRow07=0x7f060016;
        public static final int TextView01=0x7f06000e;
        public static final int TextView02=0x7f06000c;
        public static final int TwoLineListItem01=0x7f060001;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int mediacontrol=0x7f030001;
        public static final int navigation=0x7f030002;
        public static final int numberpad=0x7f030003;
    }
    public static final class string {
        public static final int add_location=0x7f05000c;
        public static final int app_name=0x7f050000;
        public static final int down=0x7f050008;
        public static final int fastforward=0x7f050006;
        public static final int left=0x7f050009;
        public static final int play=0x7f050003;
        public static final int record=0x7f050002;
        public static final int rewind=0x7f050005;
        public static final int right=0x7f05000a;
        public static final int select=0x7f05000b;
        public static final int settings_menu_str=0x7f050001;
        public static final int stop=0x7f050004;
        public static final int up=0x7f050007;
    }
    public static final class xml {
        public static final int preferences=0x7f040000;
    }
}
